# Generated by Django 4.2.2 on 2023-07-17 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_module_title'),
        ('lessons', '0002_alter_lesson_file_alter_lesson_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='modules.module', verbose_name='Module Title'),
        ),
    ]
