# Generated by Django 4.2.2 on 2023-07-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_marketplace',
            field=models.BooleanField(default=False),
        ),
    ]
