# Generated by Django 4.2.2 on 2023-07-01 22:39

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_address1',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_address2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_state',
            field=models.CharField(blank=True, max_length=50, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact_zipcode',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zip/Post Code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Instructor'), (3, 'Staff'), (4, 'Admin')], default=1),
        ),
    ]
