# Generated by Django 4.2.2 on 2023-07-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_category_alter_course_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='Category Description'),
        ),
        migrations.AddField(
            model_name='coursesubcategory',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='Subcategor Description'),
        ),
    ]
