# Generated by Django 4.2.2 on 2023-07-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('curatedcourses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedcourse',
            name='lessons',
            field=models.ManyToManyField(related_name='curated_courses', to='lessons.lesson'),
        ),
    ]
