# Generated by Django 4.2.2 on 2023-07-26 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_module_title'),
        ('lessons', '0004_lesson_is_marketplace'),
        ('courses', '0004_alter_course_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curatedcourses', '0002_alter_curatedcourse_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curatedcourse',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='curatedcourse',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='curatedcourse',
            name='price',
        ),
        migrations.RemoveField(
            model_name='curatedcourse',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='curatedcourse',
            name='title',
        ),
        migrations.AddField(
            model_name='curatedcourse',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curated_courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='curatedcourse',
            name='modules',
            field=models.ManyToManyField(null=True, related_name='curated_in_courses', to='modules.module'),
        ),
        migrations.CreateModel(
            name='ModuleBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_user_buckets', to='modules.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_buckets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LessonBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_user_buckets', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_buckets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuratedModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curated_modules', to=settings.AUTH_USER_MODEL)),
                ('lessons', models.ManyToManyField(null=True, related_name='curated_in_modules', to='lessons.lesson')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curated_modules', to='modules.module')),
            ],
        ),
    ]
