# Generated by Django 4.2.2 on 2023-08-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_alter_module_title'),
        ('lessons', '0004_lesson_is_marketplace'),
        ('curatedcourses', '0003_remove_curatedcourse_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedcourse',
            name='modules',
            field=models.ManyToManyField(related_name='curated_in_courses', to='modules.module'),
        ),
        migrations.AlterField(
            model_name='curatedmodule',
            name='lessons',
            field=models.ManyToManyField(related_name='curated_in_modules', to='lessons.lesson'),
        ),
    ]
