# Generated by Django 4.2.2 on 2023-07-13 23:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_remove_lesson_num_files_remove_module_is_preview_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='video_hours',
            new_name='videos_length',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='URL Slug'),
        ),
        migrations.DeleteModel(
            name='ModuleRating',
        ),
    ]
