# Generated by Django 4.2.2 on 2023-07-16 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curatedcourses', '0002_alter_curatedcourse_lessons'),
        ('modules', '0004_remove_module_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
